In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("datos.csv")

In [14]:
df.describe()

,id,comment_count,like_count,playcount,account_id,retweet_count,quote_count,view_count,bookmark_count,quoted_tweet_id,quoted_like_count,in_reply_to_tweet_id,conversation_id,.id
count,5.535500e+04,55355.000000,55355.000000,55355.0,5.535500e+04,55355.000000,55355.000000,5.535500e+04,55355.0,8.970000e+02,5.535500e+04,7.830000e+02,5.535100e+04,5.535500e+04
mean,1.775836e+18,17.146509,162.504453,0.0,2.325580e+15,80.239057,4.477283,2.350175e+04,0.0,1.774285e+18,2.598364e+02,1.773726e+18,1.775836e+18,1.775836e+18
std,6.894147e+15,181.386707,2153.437384,0.0,4.703448e+16,567.114404,82.243025,5.132186e+05,0.0,1.901507e+16,9.774170e+03,6.230876e+15,6.893786e+15,6.894147e+15
min,1.763763e+18,0.000000,0.000000,0.0,8.105922e+06,0.000000,0.000000,0.000000e+00,0.0,1.314580e+18,0.000000e+00,1.763740e+18,1.763740e+18,1.763763e+18
25%,1.769874e+18,0.000000,1.000000,0.0,6.064707e+07,0.000000,0.000000,1.941000e+03,0.0,1.769377e+18,0.000000e+00,1.769879e+18,1.769876e+18,1.769874e+18
50%,1.775925e+18,0.000000,4.000000,0.0,6.941652e+07,1.000000,0.000000,6.311000e+03,0.0,1.775395e+18,0.000000e+00,1.770850e+18,1.775926e+18,1.775925e+18
75%,1.781806e+18,2.000000,10.000000,0.0,8.871424e+07,6.000000,1.000000,9.720000e+03,0.0,1.781091e+18,0.000000e+00,1.778321e+18,1.781807e+18,1.781806e+18
max,1.787633e+18,15695.000000,171573.000000,0.0,9.535736e+17,31479.000000,12376.000000,9.812556e+07,0.0,1.787285e+18,1.042422e+06,1.787523e+18,1.787633e+18,1.787633e+18

In [4]:
df.columns

Index(['id', 'username', 'name', 'texto', 'comment_count', 'like_count',
       'playcount', 'url', 'source', 'scraped_at', 'time_created',
       'account_id', 'cuenta', 'retweet_count', 'quote_count', 'view_count',
       'bookmark_count', 'lang', 'is_quote_status', 'in_reply_to_user',
       'tweet_url', 'media', 'hashtags', 'user_mentions', 'is_retweet',
       'retweeted_user', 'is_quote', 'quoted_tweet_id', 'quoted_user',
       'quoted_text', 'quoted_created_at', 'quoted_like_count', 'quoted_url',
       'is_reply', 'in_reply_to_tweet_id', 'conversation_id', '.user', 'fecha',
       '.id', 'tipo', 'tramo_likes', 'es_original', 'tipo_dic', 'alcance',
       'provincia'],
      dtype='str')

In [5]:
df_propio = df[df["es_original"] == "Propio"]

In [15]:
df_propio["tipo"].value_counts()

tipo
Medio       47938
Político      931
Name: count, dtype: int64

In [13]:
df_propio.describe()

,id,comment_count,like_count,playcount,account_id,retweet_count,quote_count,view_count,bookmark_count,quoted_tweet_id,quoted_like_count,in_reply_to_tweet_id,conversation_id,.id
count,4.886900e+04,48869.000000,48869.000000,48869.0,4.886900e+04,48869.00000,48869.000000,4.886900e+04,48869.0,1.660000e+02,4.886900e+04,7.830000e+02,4.886500e+04,4.886900e+04
mean,1.775817e+18,19.422231,184.072398,0.0,1.365901e+14,31.51063,5.071518,1.995446e+04,0.0,1.773137e+18,5.514498e+01,1.773726e+18,1.775818e+18,1.775817e+18
std,6.906422e+15,192.934541,2291.027406,0.0,1.141195e+16,379.64393,87.513663,4.696086e+05,0.0,3.700262e+16,5.323796e+03,6.230876e+15,6.906017e+15,6.906422e+15
min,1.763763e+18,0.000000,0.000000,0.0,8.105922e+06,0.00000,0.000000,0.000000e+00,0.0,1.314580e+18,0.000000e+00,1.763740e+18,1.763740e+18,1.763763e+18
25%,1.769866e+18,0.000000,2.000000,0.0,6.064707e+07,0.00000,0.000000,3.094000e+03,0.0,1.770563e+18,0.000000e+00,1.769879e+18,1.769865e+18,1.769866e+18
50%,1.775898e+18,1.000000,5.000000,0.0,6.941652e+07,1.00000,0.000000,6.530000e+03,0.0,1.777420e+18,0.000000e+00,1.770850e+18,1.775899e+18,1.775898e+18
75%,1.781792e+18,3.000000,12.000000,0.0,6.941652e+07,3.00000,1.000000,9.624000e+03,0.0,1.781115e+18,0.000000e+00,1.778321e+18,1.781793e+18,1.781792e+18
max,1.787633e+18,15695.000000,171573.000000,0.0,9.535736e+17,31479.00000,12376.000000,9.812556e+07,0.0,1.787256e+18,1.042422e+06,1.787523e+18,1.787633e+18,1.787633e+18

In [10]:
df[["tipo_dic", "like_count"]].groupby(["tipo_dic"]).mean()

          like_count
tipo_dic
Medio      46.168854
Político  990.968897

In [9]:
df_propio[["tipo_dic", "like_count"]].groupby(["tipo_dic"]).mean()

           like_count
tipo_dic
Medio       46.747674
Político  7255.041890